

import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wilson
 */
public class INFORMACION extends javax.swing.JFrame {

    /**
     * Creates new form INFORMACIONDECANDIDATOS
     */
    public INFORMACION() {
        initComponents();
        this.setLocationRelativeTo(null);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnombreA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btncargarA = new javax.swing.JButton();
        btneliminarA = new javax.swing.JButton();
        btncargarB = new javax.swing.JButton();
        txtcarreraA = new javax.swing.JTextField();
        btneliminarB = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtcarreraB = new javax.swing.JTextField();
        txtnombreB = new javax.swing.JTextField();
        lblfotoA = new javax.swing.JLabel();
        lblfotoB = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        txtedadA = new javax.swing.JTextField();
        txtedadB = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 102));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("EDAD");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("CARRERA");

        jLabel7.setBackground(new java.awt.Color(0, 204, 0));
        jLabel7.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("NOMBRE");

        btncargarA.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btncargarA.setText("CARGAR FOTO");
        btncargarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarAActionPerformed(evt);
            }
        });

        btneliminarA.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btneliminarA.setText("ELIMINAR");
        btneliminarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarAActionPerformed(evt);
            }
        });

        btncargarB.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btncargarB.setText("CARGAR FOTO");
        btncargarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarBActionPerformed(evt);
            }
        });

        btneliminarB.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btneliminarB.setText("ELIMINAR");
        btneliminarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarBActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 204, 0));
        jLabel8.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("NOMBRE");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("CARRERA");

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setText("EDAD");

        lblfotoA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 5));

        lblfotoB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 5));

        btnguardar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnguardar.setText("GUARDAR Y MOSTRAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnombreA, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(txtcarreraA)
                            .addComponent(txtedadA, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btncargarA)
                        .addGap(26, 26, 26)
                        .addComponent(btneliminarA))
                    .addComponent(lblfotoA, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnombreB, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(txtcarreraB)
                            .addComponent(txtedadB, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btncargarB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btneliminarB)
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblfotoB, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnguardar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblfotoA, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfotoB, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncargarA)
                    .addComponent(btneliminarA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncargarB)
                    .addComponent(btneliminarB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtnombreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtnombreB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcarreraA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtcarreraB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txtedadA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtedadB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnguardar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncargarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarAActionPerformed

        int resultado;
        Cargarimagen ventana= new Cargarimagen();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("PNG","JPG","png","jpg");
        Cargarimagen.jfcargarfoto.setFileFilter(filtro);
        resultado=Cargarimagen.jfcargarfoto.showOpenDialog(null);
        if(JFileChooser.APPROVE_OPTION == resultado){
            fichero = Cargarimagen.jfcargarfoto.getSelectedFile();
            try{
                ImageIcon icon = new ImageIcon(fichero.toString());
                Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lblfotoA.getWidth(),lblfotoA.getHeight(),Image.SCALE_DEFAULT));
                lblfotoA.setIcon(icono);
            }catch (Exception ex){
                JOptionPane.showMessageDialog(this, "error al cargar la imagen"  + ex);
            }
        }

    }//GEN-LAST:event_btncargarAActionPerformed

    private void btneliminarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarAActionPerformed
        
        if(btneliminarA == btneliminarA){
            lblfotoA.setIcon(null);
        }
    }//GEN-LAST:event_btneliminarAActionPerformed

    private void btncargarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarBActionPerformed
        // TODO add your handling code here:
        int resultado;
        Cargarimagen ventana= new Cargarimagen();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("PNG","JPG","png","jpg","JPEG","jpeg");
        Cargarimagen.jfcargarfoto.setFileFilter(filtro);
        resultado=Cargarimagen.jfcargarfoto.showOpenDialog(null);
        if(JFileChooser.APPROVE_OPTION == resultado){
            fichero = Cargarimagen.jfcargarfoto.getSelectedFile();
            try{
                ImageIcon icon = new ImageIcon(fichero.toString());
                Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lblfotoB.getWidth(),lblfotoB.getHeight(),Image.SCALE_DEFAULT));
                lblfotoB.setIcon(icono);
            }catch (Exception ex){
                JOptionPane.showMessageDialog(this, "error al cargar la imagen"  + ex);
            }
        }
    }//GEN-LAST:event_btncargarBActionPerformed

    private void btneliminarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarBActionPerformed
        // TODO add your handling code here:
        if(btneliminarB== btneliminarB){
            lblfotoB.setIcon(null);
        }
    }//GEN-LAST:event_btneliminarBActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TOiconDO add your handling code here:
       
        if(btnguardar == btnguardar){
            INFOGUARDAR objForm = new INFOGUARDAR();
            objForm.setVisible(true);
            dispose();   
            INFOGUARDAR.lblfotoA.setIcon(lblfotoA.getIcon());
            INFOGUARDAR.lblfotoB.setIcon(lblfotoB.getIcon());
            INFOGUARDAR.lblnombreA.setText(txtnombreA.getText());
            INFOGUARDAR.lblcarreraA.setText(txtcarreraA.getText());
            INFOGUARDAR.lbledadA.setText(txtedadA.getText());
            INFOGUARDAR.lblnombreB.setText(txtnombreB.getText());
            INFOGUARDAR.lblcarreraB.setText(txtcarreraB.getText());
            INFOGUARDAR.lbledadB.setText(txtedadB.getText());
        }
                
                
        
    }//GEN-LAST:event_btnguardarActionPerformed

    
    File fichero;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INFORMACION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new INFORMACION().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncargarA;
    private javax.swing.JButton btncargarB;
    private javax.swing.JButton btneliminarA;
    private javax.swing.JButton btneliminarB;
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel lblfotoA;
    public static javax.swing.JLabel lblfotoB;
    public static javax.swing.JTextField txtcarreraA;
    public static javax.swing.JTextField txtcarreraB;
    private javax.swing.JTextField txtedadA;
    private javax.swing.JTextField txtedadB;
    public static javax.swing.JTextField txtnombreA;
    public static javax.swing.JTextField txtnombreB;
    // End of variables declaration//GEN-END:variables
}
